### ISSUE TITLE
Chapter 2 (JiYoun) - Top Scores

### ISSUE THREAD

**Issue by royc0003** [royc0003/AlgoInterview#21]

**Comment by jollyjiyoun** [comment]
import unittest

```
def sort_scores(unsorted_scores, highest_possible_score):

    # initialize array for sorted_scores, lis
    sorted_scores=[]
    lis=[0]*(highest_possible_score+1)
    #put the frequency of score in lis, O(n) time
    for i in unsorted_scores:
        lis[i]+=1
    #iterate through lis and append the index of list based on frequency, O(1) time, O(n) space
    for j in range(highest_possible_score,0,-1):
        while lis[j]>0:
            sorted_scores.append(j)
            lis[j]-=1

    return sorted_scores
```

**Comment by jollyjiyoun** [comment]
```
import unittest


def sort_scores(unsorted_scores, highest_possible_score):

    # initialize array for sorted_scores, lis
    sorted_scores=[]
    lis=[0]*(highest_possible_score+1)
    #put the frequency of score in lis, O(n) time
    for i in unsorted_scores:
        lis[i]+=1
    #iterate through lis and append the index of list based on frequency, O(1) time, O(n) space
    for j in range(highest_possible_score,0,-1):
        while lis[j]>0:
            sorted_scores.append(j)
            lis[j]-=1

    return sorted_scores
```

**Comment by jollyjiyoun** [comment]
Initially I had thought of the idea of storing the elements in a new list based on index, however, I had to reference the answers before coding the solution.

This was because I was concerned that the list size would be too huge if we initialize a list of (highest_possible_score) size, and iterating through this list would take too much time.

However, the question states that the 'highest_possible_score' would be considered a constant.

In future problem solvings, I would understand the question better, and just try any solution that I think would be possible instead of feeling concerned.

**Comment by jollyjiyoun** [comment]
The time is O(n), space O(n) in this solution.

If highest_possible_score is not considered a constant, but 'm' instead, the time complexity would be O(n+m), and space complexity O(n) because the list of size O(m) can be freed after the solution is provided.
