### ISSUE TITLE
Chapter 3 (JiYoun) - Apple Stocks

### ISSUE THREAD

**Issue by royc0003** [royc0003/AlgoInterview#22]

**Comment by jollyjiyoun** [comment]
```
def get_max_profit(stock_prices):

    # get the length of list
    n=len(stock_prices)
    # length has to be at least 2
    if n<2:
        raise ValueError(stock_prices)
    #for every iteration, compute currentval - previous minval(comp)
    #compare minval until now and currentval -> update minval
    #compare maxval until now and comp -> update maxval
    minval=stock_prices[0]
    for i in range(1,n):
        comp=stock_prices[i]-minval
        minval=min(minval, stock_prices[i])
        if i==1:
            maxval=comp
        else:
            maxval=max(maxval,comp)

    return maxval
```

**Comment by jollyjiyoun** [comment]
Initially, I thought that I should find the maximum value, minimum value, and check whether the maximum value index is higher than the minimum value index. Therefore, I thought I had to sort it, and then continuously compare the indexes of the small and large numbers. However, not only would this method be complicated due to the comparing algorithm, but also it would take O(n^2) time, which would be no different with the straight-forward brute-force method.

**Comment by jollyjiyoun** [comment]
Using the greedy method, I could store and compare the maximum difference result, and update the minimum value. This is possible in O(n) time, O(1) space complexity. 

When solving problems, I should think whether there is a way to loop through the list once, and update consistently the best possible result and variables needed to solve the problem.
