### ISSUE TITLE
Chapter 5 (Jiyoun) - Balanced Search Tree Checker

### ISSUE THREAD

**Issue by royc0003** [royc0003/AlgoInterview#42]

**Comment by jollyjiyoun** [comment]
```
import unittest


def is_binary_search_tree(root):

    queue=[]
    queue.append(root)
    #using bfs, check if largest smaller node value < current node value
    #and smallest larger node value > current node value
    while queue:
        node=queue.pop(0)
        if node.left:
            lnode=node.left
            queue.append(lnode)
            while lnode.right:
                lnode=lnode.right
            if node.value<lnode.value:
                return False
        if node.right:
            rnode=node.right
            queue.append(rnode)
            while rnode.left:
                rnode=rnode.left
            if node.value>rnode.value:
                return False

    return True
```

**Comment by jollyjiyoun** [comment]
The above code uses BFS and while looping through each node, checks whether the largest smaller node value is smaller than the current node value, and the smallest larger node value is larger than the current node value. The time complexity is O(nlogn) and space complexity is O(n).

**Comment by jollyjiyoun** [comment]
```
import unittest


def is_binary_search_tree(root):

    stack=[]
    stack.append((root, -float("inf"), float("inf")))
    while stack:
        node, low_bound, high_bound=stack.pop()
        if low_bound>node.value or high_bound<node.value:
            return False
        if node.right:
            stack.append((node.right, node.value, high_bound))
        if node.left:
            stack.append((node.left, low_bound, node.value))

    return True
```

**Comment by jollyjiyoun** [comment]
The code above uses DFS and has O(n) time complexity, O(n) space complexity. 

I used DFS because BFS and DFS have the same time complexity, but DFS costs less space complexity.

The first solution I coded compares the current node's values with it's descendants, while the solution above compares the current node's values with it's ascendants. Therefore, the first solution costs more time complexity, O(nlogn) compared to the second solution, O(n). This is because the current comparing node is iterated from root to bottom, and if the descendent comparison method is used, it would require additional time to loop down the descendants, as these descendants were not tracked before. However comparing the current node with it's ascendants costs less time because it can simply store the ascendant node values while tracking through the nodes from root to bottom, which does not cost additional time to search the comparison nodes.
